# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bot_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bot_api.proto',
  package='yarn',
  syntax='proto3',
  serialized_pb=_b('\n\rbot_api.proto\x12\x04yarn\x1a\x0c\x63ommon.proto\"\xab\x01\n\rBotInvocation\x12\x17\n\x03\x62ot\x18\x01 \x01(\x0b\x32\n.yarn.User\x12#\n\x07mention\x18\x02 \x01(\x0b\x32\x10.yarn.BotMentionH\x00\x12%\n\x08\x64\x65livery\x18\x03 \x01(\x0b\x32\x11.yarn.BotDeliveryH\x00\x12-\n\nsubmission\x18\x04 \x01(\x0b\x32\x17.yarn.BotFormSubmissionH\x00\x42\x06\n\x04\x63\x61ll\"J\n\nBotMention\x12\x1c\n\x06thread\x18\x01 \x01(\x0b\x32\x0c.yarn.Thread\x12\x1e\n\x07message\x18\x02 \x01(\x0b\x32\r.yarn.Message\"v\n\x0b\x42otDelivery\x12\x1c\n\x06thread\x18\x01 \x01(\x0b\x32\x0c.yarn.Thread\x12 \n\x07message\x18\x02 \x01(\x0b\x32\r.yarn.MessageH\x00\x12\x1c\n\x05\x65vent\x18\x03 \x01(\x0b\x32\x0b.yarn.EventH\x00\x42\t\n\x07payload\"G\n\x11\x42otFormSubmission\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.yarn.User\x12\x18\n\x04\x66orm\x18\x02 \x01(\x0b\x32\n.yarn.Form\"4\n\x12\x42otInvocationReply\x12\x1e\n\x07message\x18\x01 \x01(\x0b\x32\r.yarn.Message\"\xb4\x01\n\x07\x42otCall\x12\x17\n\x03\x62ot\x18\x01 \x01(\x0b\x32\n.yarn.User\x12\x1e\n\x06thread\x18\x02 \x01(\x0b\x32\x0c.yarn.ThreadH\x00\x12\x1a\n\x04user\x18\x03 \x01(\x0b\x32\n.yarn.UserH\x00\x12 \n\x07message\x18\x04 \x01(\x0b\x32\r.yarn.MessageH\x01\x12\x1a\n\x04\x66orm\x18\x05 \x01(\x0b\x32\n.yarn.FormH\x01\x42\x0b\n\trecipientB\t\n\x07payloadB\x04Z\x02pbb\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BOTINVOCATION = _descriptor.Descriptor(
  name='BotInvocation',
  full_name='yarn.BotInvocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bot', full_name='yarn.BotInvocation.bot', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mention', full_name='yarn.BotInvocation.mention', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delivery', full_name='yarn.BotInvocation.delivery', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='submission', full_name='yarn.BotInvocation.submission', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='call', full_name='yarn.BotInvocation.call',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=38,
  serialized_end=209,
)


_BOTMENTION = _descriptor.Descriptor(
  name='BotMention',
  full_name='yarn.BotMention',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thread', full_name='yarn.BotMention.thread', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='yarn.BotMention.message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=285,
)


_BOTDELIVERY = _descriptor.Descriptor(
  name='BotDelivery',
  full_name='yarn.BotDelivery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thread', full_name='yarn.BotDelivery.thread', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='yarn.BotDelivery.message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event', full_name='yarn.BotDelivery.event', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='yarn.BotDelivery.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=287,
  serialized_end=405,
)


_BOTFORMSUBMISSION = _descriptor.Descriptor(
  name='BotFormSubmission',
  full_name='yarn.BotFormSubmission',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='yarn.BotFormSubmission.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='form', full_name='yarn.BotFormSubmission.form', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=478,
)


_BOTINVOCATIONREPLY = _descriptor.Descriptor(
  name='BotInvocationReply',
  full_name='yarn.BotInvocationReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='yarn.BotInvocationReply.message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=532,
)


_BOTCALL = _descriptor.Descriptor(
  name='BotCall',
  full_name='yarn.BotCall',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bot', full_name='yarn.BotCall.bot', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thread', full_name='yarn.BotCall.thread', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user', full_name='yarn.BotCall.user', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='yarn.BotCall.message', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='form', full_name='yarn.BotCall.form', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='recipient', full_name='yarn.BotCall.recipient',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='payload', full_name='yarn.BotCall.payload',
      index=1, containing_type=None, fields=[]),
  ],
  serialized_start=535,
  serialized_end=715,
)

_BOTINVOCATION.fields_by_name['bot'].message_type = common__pb2._USER
_BOTINVOCATION.fields_by_name['mention'].message_type = _BOTMENTION
_BOTINVOCATION.fields_by_name['delivery'].message_type = _BOTDELIVERY
_BOTINVOCATION.fields_by_name['submission'].message_type = _BOTFORMSUBMISSION
_BOTINVOCATION.oneofs_by_name['call'].fields.append(
  _BOTINVOCATION.fields_by_name['mention'])
_BOTINVOCATION.fields_by_name['mention'].containing_oneof = _BOTINVOCATION.oneofs_by_name['call']
_BOTINVOCATION.oneofs_by_name['call'].fields.append(
  _BOTINVOCATION.fields_by_name['delivery'])
_BOTINVOCATION.fields_by_name['delivery'].containing_oneof = _BOTINVOCATION.oneofs_by_name['call']
_BOTINVOCATION.oneofs_by_name['call'].fields.append(
  _BOTINVOCATION.fields_by_name['submission'])
_BOTINVOCATION.fields_by_name['submission'].containing_oneof = _BOTINVOCATION.oneofs_by_name['call']
_BOTMENTION.fields_by_name['thread'].message_type = common__pb2._THREAD
_BOTMENTION.fields_by_name['message'].message_type = common__pb2._MESSAGE
_BOTDELIVERY.fields_by_name['thread'].message_type = common__pb2._THREAD
_BOTDELIVERY.fields_by_name['message'].message_type = common__pb2._MESSAGE
_BOTDELIVERY.fields_by_name['event'].message_type = common__pb2._EVENT
_BOTDELIVERY.oneofs_by_name['payload'].fields.append(
  _BOTDELIVERY.fields_by_name['message'])
_BOTDELIVERY.fields_by_name['message'].containing_oneof = _BOTDELIVERY.oneofs_by_name['payload']
_BOTDELIVERY.oneofs_by_name['payload'].fields.append(
  _BOTDELIVERY.fields_by_name['event'])
_BOTDELIVERY.fields_by_name['event'].containing_oneof = _BOTDELIVERY.oneofs_by_name['payload']
_BOTFORMSUBMISSION.fields_by_name['user'].message_type = common__pb2._USER
_BOTFORMSUBMISSION.fields_by_name['form'].message_type = common__pb2._FORM
_BOTINVOCATIONREPLY.fields_by_name['message'].message_type = common__pb2._MESSAGE
_BOTCALL.fields_by_name['bot'].message_type = common__pb2._USER
_BOTCALL.fields_by_name['thread'].message_type = common__pb2._THREAD
_BOTCALL.fields_by_name['user'].message_type = common__pb2._USER
_BOTCALL.fields_by_name['message'].message_type = common__pb2._MESSAGE
_BOTCALL.fields_by_name['form'].message_type = common__pb2._FORM
_BOTCALL.oneofs_by_name['recipient'].fields.append(
  _BOTCALL.fields_by_name['thread'])
_BOTCALL.fields_by_name['thread'].containing_oneof = _BOTCALL.oneofs_by_name['recipient']
_BOTCALL.oneofs_by_name['recipient'].fields.append(
  _BOTCALL.fields_by_name['user'])
_BOTCALL.fields_by_name['user'].containing_oneof = _BOTCALL.oneofs_by_name['recipient']
_BOTCALL.oneofs_by_name['payload'].fields.append(
  _BOTCALL.fields_by_name['message'])
_BOTCALL.fields_by_name['message'].containing_oneof = _BOTCALL.oneofs_by_name['payload']
_BOTCALL.oneofs_by_name['payload'].fields.append(
  _BOTCALL.fields_by_name['form'])
_BOTCALL.fields_by_name['form'].containing_oneof = _BOTCALL.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['BotInvocation'] = _BOTINVOCATION
DESCRIPTOR.message_types_by_name['BotMention'] = _BOTMENTION
DESCRIPTOR.message_types_by_name['BotDelivery'] = _BOTDELIVERY
DESCRIPTOR.message_types_by_name['BotFormSubmission'] = _BOTFORMSUBMISSION
DESCRIPTOR.message_types_by_name['BotInvocationReply'] = _BOTINVOCATIONREPLY
DESCRIPTOR.message_types_by_name['BotCall'] = _BOTCALL

BotInvocation = _reflection.GeneratedProtocolMessageType('BotInvocation', (_message.Message,), dict(
  DESCRIPTOR = _BOTINVOCATION,
  __module__ = 'bot_api_pb2'
  # @@protoc_insertion_point(class_scope:yarn.BotInvocation)
  ))
_sym_db.RegisterMessage(BotInvocation)

BotMention = _reflection.GeneratedProtocolMessageType('BotMention', (_message.Message,), dict(
  DESCRIPTOR = _BOTMENTION,
  __module__ = 'bot_api_pb2'
  # @@protoc_insertion_point(class_scope:yarn.BotMention)
  ))
_sym_db.RegisterMessage(BotMention)

BotDelivery = _reflection.GeneratedProtocolMessageType('BotDelivery', (_message.Message,), dict(
  DESCRIPTOR = _BOTDELIVERY,
  __module__ = 'bot_api_pb2'
  # @@protoc_insertion_point(class_scope:yarn.BotDelivery)
  ))
_sym_db.RegisterMessage(BotDelivery)

BotFormSubmission = _reflection.GeneratedProtocolMessageType('BotFormSubmission', (_message.Message,), dict(
  DESCRIPTOR = _BOTFORMSUBMISSION,
  __module__ = 'bot_api_pb2'
  # @@protoc_insertion_point(class_scope:yarn.BotFormSubmission)
  ))
_sym_db.RegisterMessage(BotFormSubmission)

BotInvocationReply = _reflection.GeneratedProtocolMessageType('BotInvocationReply', (_message.Message,), dict(
  DESCRIPTOR = _BOTINVOCATIONREPLY,
  __module__ = 'bot_api_pb2'
  # @@protoc_insertion_point(class_scope:yarn.BotInvocationReply)
  ))
_sym_db.RegisterMessage(BotInvocationReply)

BotCall = _reflection.GeneratedProtocolMessageType('BotCall', (_message.Message,), dict(
  DESCRIPTOR = _BOTCALL,
  __module__ = 'bot_api_pb2'
  # @@protoc_insertion_point(class_scope:yarn.BotCall)
  ))
_sym_db.RegisterMessage(BotCall)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\002pb'))
# @@protoc_insertion_point(module_scope)
